# syntax=docker/dockerfile:1

# Build stage
FROM rust:1.85-bookworm AS builder
WORKDIR /app
COPY . .
RUN cargo fetch
RUN cargo build -r -p kickflip-client

# Runtime stage
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates openssh-client && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/bin
COPY --from=builder /app/target/release/kickflip-client /usr/local/bin/kickflip-client

ENTRYPOINT ["/usr/local/bin/kickflip-client"]
