#!/bin/bash
# Kickflip Server Installer (Docker Compose)
# Usage: curl -fsSL https://raw.githubusercontent.com/jb-san/kickflip/main/scripts/install-server.sh | bash

set -e

REPO="jb-san/kickflip"
BRANCH="main"
INSTALL_DIR="${INSTALL_DIR:-/opt/kickflip}"
CONFIG_DIR="${CONFIG_DIR:-/etc/kickflip}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
prompt() { echo -e "${CYAN}[?]${NC} $1"; }

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Kickflip Server Installer         ║${NC}"
echo -e "${GREEN}║     (Docker Compose Edition)          ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════╝${NC}"
echo ""

# Check requirements
info "Checking requirements..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
fi

if ! command -v docker compose &>/dev/null && ! command -v docker-compose &>/dev/null; then
    error "Docker Compose is not installed. Please install it first."
fi
success "Docker and Docker Compose are installed"

# Check if docker is running
if ! docker info &>/dev/null; then
    error "Docker is not running. Please start Docker first."
fi
success "Docker is running"

# Create directories
info "Creating directories..."
sudo mkdir -p "${INSTALL_DIR}"
sudo mkdir -p "${CONFIG_DIR}/clients.d"
sudo mkdir -p "${CONFIG_DIR}/letsencrypt"
sudo mkdir -p "${CONFIG_DIR}/nginx/sites-available"
sudo mkdir -p "${CONFIG_DIR}/nginx/sites-enabled"
success "Created ${INSTALL_DIR} and ${CONFIG_DIR}"

# Download docker-compose.yml
info "Downloading docker-compose.yml..."
COMPOSE_URL="https://raw.githubusercontent.com/${REPO}/${BRANCH}/docker-compose.yml"
sudo curl -fsSL -o "${INSTALL_DIR}/docker-compose.yml" "${COMPOSE_URL}"
success "Downloaded docker-compose.yml"

# Get configuration from user
echo ""
echo -e "${YELLOW}═══════════════════════════════════════${NC}"
echo -e "${YELLOW}  Server Configuration${NC}"
echo -e "${YELLOW}═══════════════════════════════════════${NC}"
echo ""

# Domain
prompt "Enter your domain (e.g., example.com):"
read -r DOMAIN
if [ -z "${DOMAIN}" ]; then
    error "Domain is required"
fi

# Email for Let's Encrypt
prompt "Enter your email for Let's Encrypt certificates:"
read -r EMAIL
if [ -z "${EMAIL}" ]; then
    error "Email is required for SSL certificates"
fi

# Auto SSL
prompt "Enable automatic SSL certificates? [Y/n]"
read -r AUTO_SSL
AUTO_SSL=${AUTO_SSL:-Y}
if [[ "${AUTO_SSL}" =~ ^[Yy]$ ]]; then
    AUTO_CERT="true"
    TLS_ENABLE="true"
else
    AUTO_CERT="false"
    TLS_ENABLE="false"
fi

# Create config file
info "Creating configuration..."
sudo tee "${CONFIG_DIR}/kickflip-server.toml" > /dev/null << EOF
# Kickflip Server Configuration
# Generated by install-server.sh

rp_id = "${DOMAIN}"
acme_email = "${EMAIL}"
auto_cert = ${AUTO_CERT}
tls_enable = ${TLS_ENABLE}
http_redirect = ${TLS_ENABLE}
EOF
success "Created ${CONFIG_DIR}/kickflip-server.toml"

# Update docker-compose.yml with correct paths
info "Configuring docker-compose.yml..."
cd "${INSTALL_DIR}"

# Create a local override for the config path
sudo tee "${INSTALL_DIR}/docker-compose.override.yml" > /dev/null << EOF
services:
  kickflip:
    volumes:
      - ${CONFIG_DIR}/kickflip-server.toml:/etc/kickflip/kickflip-server.toml:ro
      - ${CONFIG_DIR}/clients.d:/etc/kickflip/clients.d
      - ${CONFIG_DIR}/letsencrypt:/etc/letsencrypt
      - ${CONFIG_DIR}/nginx/sites-available:/etc/nginx/sites-available
      - ${CONFIG_DIR}/nginx/sites-enabled:/etc/nginx/sites-enabled
EOF
success "Created docker-compose.override.yml"

# Add shell alias
SHELL_RC=""
case "${SHELL}" in
    */zsh)  SHELL_RC="$HOME/.zshrc" ;;
    */bash) SHELL_RC="$HOME/.bashrc" ;;
    *)      SHELL_RC="" ;;
esac

if [ -n "${SHELL_RC}" ]; then
    echo ""
    prompt "Would you like to add a 'kfs' alias for managing the server? [Y/n]"
    read -r ADD_ALIAS
    ADD_ALIAS=${ADD_ALIAS:-Y}
    
    if [[ "${ADD_ALIAS}" =~ ^[Yy]$ ]]; then
        ALIAS_CMD="alias kfs='docker compose -f ${INSTALL_DIR}/docker-compose.yml -f ${INSTALL_DIR}/docker-compose.override.yml exec kickflip kickflip-server'"
        
        if ! grep -q "alias kfs=" "${SHELL_RC}" 2>/dev/null; then
            echo "" >> "${SHELL_RC}"
            echo "# Kickflip server alias" >> "${SHELL_RC}"
            echo "${ALIAS_CMD}" >> "${SHELL_RC}"
            success "Added 'kfs' alias to ${SHELL_RC}"
            warn "Run 'source ${SHELL_RC}' to use the alias"
        else
            info "Alias 'kfs' already exists in ${SHELL_RC}"
        fi
    fi
fi

# DNS reminder
echo ""
echo -e "${YELLOW}═══════════════════════════════════════${NC}"
echo -e "${YELLOW}  DNS Configuration Required!${NC}"
echo -e "${YELLOW}═══════════════════════════════════════${NC}"
echo ""
echo "Before starting the server, configure your DNS:"
echo ""
echo -e "  ${CYAN}A Record:${NC}    ${DOMAIN}     -> YOUR_SERVER_IP"
echo -e "  ${CYAN}A Record:${NC}    *.${DOMAIN}   -> YOUR_SERVER_IP"
echo ""
echo "Replace YOUR_SERVER_IP with your server's public IP address."
echo ""

# Start server?
prompt "Start the server now? [Y/n]"
read -r START_NOW
START_NOW=${START_NOW:-Y}

if [[ "${START_NOW}" =~ ^[Yy]$ ]]; then
    info "Starting Kickflip server..."
    cd "${INSTALL_DIR}"
    sudo docker compose pull
    sudo docker compose up -d
    
    echo ""
    info "Waiting for server to start..."
    sleep 5
    
    # Health check
    if curl -sf "http://localhost:8080/health" > /dev/null 2>&1; then
        success "Server is running!"
    else
        warn "Server may still be starting. Check with: docker compose logs -f"
    fi
fi

echo ""
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}  Installation complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo ""
echo "Useful commands:"
echo ""
echo -e "  ${CYAN}Start server:${NC}      cd ${INSTALL_DIR} && docker compose up -d"
echo -e "  ${CYAN}Stop server:${NC}       cd ${INSTALL_DIR} && docker compose down"
echo -e "  ${CYAN}View logs:${NC}         cd ${INSTALL_DIR} && docker compose logs -f"
echo -e "  ${CYAN}Server status:${NC}     kfs status  (after sourcing shell)"
echo -e "  ${CYAN}Add client:${NC}        kfs add-client --pubkey 'ssh-ed25519 ...' --name client1"
echo ""
echo "Config files:"
echo -e "  ${CYAN}Server config:${NC}     ${CONFIG_DIR}/kickflip-server.toml"
echo -e "  ${CYAN}Client keys:${NC}       ${CONFIG_DIR}/clients.d/"
echo -e "  ${CYAN}SSL certs:${NC}         ${CONFIG_DIR}/letsencrypt/"
echo ""
echo "Documentation: https://github.com/${REPO}"
echo ""

